arb-dir: lib/src/l10n
template-arb-file: messages_en.arb.arb
output-localization-file: home_screen_localization.dart
output-class: HomeScreenLocalizations
synthetic-package: false
nullable-getter: false