arb-dir: lib/src/l10n
template-arb-file: messages_en.arb
output-localization-file: upload_screen_localization.dart
output-class: UploadScreenLocalizations
synthetic-package: false
nullable-getter: false