arb-dir: lib/src/l10n
template-arb-file: messages_en.arb.arb
output-localization-file: category_screen_localization.dart
output-class: CategoryScreenLocalizations
synthetic-package: false
nullable-getter: false